// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Province is the predicate function for province builders.
type Province func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserType is the predicate function for usertype builders.
type UserType func(*sql.Selector)
