// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/james/app/ent/predicate"
	"github.com/james/app/ent/usertype"
)

// UserTypeDelete is the builder for deleting a UserType entity.
type UserTypeDelete struct {
	config
	hooks      []Hook
	mutation   *UserTypeMutation
	predicates []predicate.UserType
}

// Where adds a new predicate to the delete builder.
func (utd *UserTypeDelete) Where(ps ...predicate.UserType) *UserTypeDelete {
	utd.predicates = append(utd.predicates, ps...)
	return utd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (utd *UserTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(utd.hooks) == 0 {
		affected, err = utd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			utd.mutation = mutation
			affected, err = utd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(utd.hooks) - 1; i >= 0; i-- {
			mut = utd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, utd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (utd *UserTypeDelete) ExecX(ctx context.Context) int {
	n, err := utd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (utd *UserTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usertype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertype.FieldID,
			},
		},
	}
	if ps := utd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, utd.driver, _spec)
}

// UserTypeDeleteOne is the builder for deleting a single UserType entity.
type UserTypeDeleteOne struct {
	utd *UserTypeDelete
}

// Exec executes the deletion query.
func (utdo *UserTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := utdo.utd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (utdo *UserTypeDeleteOne) ExecX(ctx context.Context) {
	utdo.utd.ExecX(ctx)
}
