// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/james/app/ent/gender"
	"github.com/james/app/ent/province"
	"github.com/james/app/ent/user"
	"github.com/james/app/ent/usertype"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetIdentityCard sets the Identity_card field.
func (uc *UserCreate) SetIdentityCard(i int) *UserCreate {
	uc.mutation.SetIdentityCard(i)
	return uc
}

// SetPassword sets the Password field.
func (uc *UserCreate) SetPassword(s string) *UserCreate {
	uc.mutation.SetPassword(s)
	return uc
}

// SetConfirmPassword sets the Confirm_password field.
func (uc *UserCreate) SetConfirmPassword(s string) *UserCreate {
	uc.mutation.SetConfirmPassword(s)
	return uc
}

// SetFirstName sets the First_name field.
func (uc *UserCreate) SetFirstName(s string) *UserCreate {
	uc.mutation.SetFirstName(s)
	return uc
}

// SetLastName sets the Last_name field.
func (uc *UserCreate) SetLastName(s string) *UserCreate {
	uc.mutation.SetLastName(s)
	return uc
}

// SetEmail sets the Email field.
func (uc *UserCreate) SetEmail(s string) *UserCreate {
	uc.mutation.SetEmail(s)
	return uc
}

// SetPhone sets the Phone field.
func (uc *UserCreate) SetPhone(i int) *UserCreate {
	uc.mutation.SetPhone(i)
	return uc
}

// SetDateOfBirth sets the Date_of_birth field.
func (uc *UserCreate) SetDateOfBirth(i int) *UserCreate {
	uc.mutation.SetDateOfBirth(i)
	return uc
}

// SetGenderIDID sets the Gender_ID edge to Gender by id.
func (uc *UserCreate) SetGenderIDID(id int) *UserCreate {
	uc.mutation.SetGenderIDID(id)
	return uc
}

// SetNillableGenderIDID sets the Gender_ID edge to Gender by id if the given value is not nil.
func (uc *UserCreate) SetNillableGenderIDID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetGenderIDID(*id)
	}
	return uc
}

// SetGenderID sets the Gender_ID edge to Gender.
func (uc *UserCreate) SetGenderID(g *Gender) *UserCreate {
	return uc.SetGenderIDID(g.ID)
}

// SetUserTypeIDID sets the UserType_ID edge to UserType by id.
func (uc *UserCreate) SetUserTypeIDID(id int) *UserCreate {
	uc.mutation.SetUserTypeIDID(id)
	return uc
}

// SetNillableUserTypeIDID sets the UserType_ID edge to UserType by id if the given value is not nil.
func (uc *UserCreate) SetNillableUserTypeIDID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetUserTypeIDID(*id)
	}
	return uc
}

// SetUserTypeID sets the UserType_ID edge to UserType.
func (uc *UserCreate) SetUserTypeID(u *UserType) *UserCreate {
	return uc.SetUserTypeIDID(u.ID)
}

// SetProvinceIDID sets the Province_ID edge to Province by id.
func (uc *UserCreate) SetProvinceIDID(id int) *UserCreate {
	uc.mutation.SetProvinceIDID(id)
	return uc
}

// SetNillableProvinceIDID sets the Province_ID edge to Province by id if the given value is not nil.
func (uc *UserCreate) SetNillableProvinceIDID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetProvinceIDID(*id)
	}
	return uc
}

// SetProvinceID sets the Province_ID edge to Province.
func (uc *UserCreate) SetProvinceID(p *Province) *UserCreate {
	return uc.SetProvinceIDID(p.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if _, ok := uc.mutation.IdentityCard(); !ok {
		return nil, &ValidationError{Name: "Identity_card", err: errors.New("ent: missing required field \"Identity_card\"")}
	}
	if v, ok := uc.mutation.IdentityCard(); ok {
		if err := user.IdentityCardValidator(v); err != nil {
			return nil, &ValidationError{Name: "Identity_card", err: fmt.Errorf("ent: validator failed for field \"Identity_card\": %w", err)}
		}
	}
	if _, ok := uc.mutation.Password(); !ok {
		return nil, &ValidationError{Name: "Password", err: errors.New("ent: missing required field \"Password\"")}
	}
	if v, ok := uc.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return nil, &ValidationError{Name: "Password", err: fmt.Errorf("ent: validator failed for field \"Password\": %w", err)}
		}
	}
	if _, ok := uc.mutation.ConfirmPassword(); !ok {
		return nil, &ValidationError{Name: "Confirm_password", err: errors.New("ent: missing required field \"Confirm_password\"")}
	}
	if v, ok := uc.mutation.ConfirmPassword(); ok {
		if err := user.ConfirmPasswordValidator(v); err != nil {
			return nil, &ValidationError{Name: "Confirm_password", err: fmt.Errorf("ent: validator failed for field \"Confirm_password\": %w", err)}
		}
	}
	if _, ok := uc.mutation.FirstName(); !ok {
		return nil, &ValidationError{Name: "First_name", err: errors.New("ent: missing required field \"First_name\"")}
	}
	if v, ok := uc.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "First_name", err: fmt.Errorf("ent: validator failed for field \"First_name\": %w", err)}
		}
	}
	if _, ok := uc.mutation.LastName(); !ok {
		return nil, &ValidationError{Name: "Last_name", err: errors.New("ent: missing required field \"Last_name\"")}
	}
	if v, ok := uc.mutation.LastName(); ok {
		if err := user.LastNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Last_name", err: fmt.Errorf("ent: validator failed for field \"Last_name\": %w", err)}
		}
	}
	if _, ok := uc.mutation.Email(); !ok {
		return nil, &ValidationError{Name: "Email", err: errors.New("ent: missing required field \"Email\"")}
	}
	if v, ok := uc.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return nil, &ValidationError{Name: "Email", err: fmt.Errorf("ent: validator failed for field \"Email\": %w", err)}
		}
	}
	if _, ok := uc.mutation.Phone(); !ok {
		return nil, &ValidationError{Name: "Phone", err: errors.New("ent: missing required field \"Phone\"")}
	}
	if v, ok := uc.mutation.Phone(); ok {
		if err := user.PhoneValidator(v); err != nil {
			return nil, &ValidationError{Name: "Phone", err: fmt.Errorf("ent: validator failed for field \"Phone\": %w", err)}
		}
	}
	if _, ok := uc.mutation.DateOfBirth(); !ok {
		return nil, &ValidationError{Name: "Date_of_birth", err: errors.New("ent: missing required field \"Date_of_birth\"")}
	}
	if v, ok := uc.mutation.DateOfBirth(); ok {
		if err := user.DateOfBirthValidator(v); err != nil {
			return nil, &ValidationError{Name: "Date_of_birth", err: fmt.Errorf("ent: validator failed for field \"Date_of_birth\": %w", err)}
		}
	}
	var (
		err  error
		node *User
	)
	if len(uc.hooks) == 0 {
		node, err = uc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uc.mutation = mutation
			node, err = uc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uc.hooks) - 1; i >= 0; i-- {
			mut = uc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	u, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	u.ID = int(id)
	return u, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		u     = &User{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: user.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		}
	)
	if value, ok := uc.mutation.IdentityCard(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldIdentityCard,
		})
		u.IdentityCard = value
	}
	if value, ok := uc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldPassword,
		})
		u.Password = value
	}
	if value, ok := uc.mutation.ConfirmPassword(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldConfirmPassword,
		})
		u.ConfirmPassword = value
	}
	if value, ok := uc.mutation.FirstName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldFirstName,
		})
		u.FirstName = value
	}
	if value, ok := uc.mutation.LastName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldLastName,
		})
		u.LastName = value
	}
	if value, ok := uc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldEmail,
		})
		u.Email = value
	}
	if value, ok := uc.mutation.Phone(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldPhone,
		})
		u.Phone = value
	}
	if value, ok := uc.mutation.DateOfBirth(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldDateOfBirth,
		})
		u.DateOfBirth = value
	}
	if nodes := uc.mutation.GenderIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.GenderIDTable,
			Columns: []string{user.GenderIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UserTypeIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserTypeIDTable,
			Columns: []string{user.UserTypeIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: usertype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ProvinceIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ProvinceIDTable,
			Columns: []string{user.ProvinceIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: province.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return u, _spec
}
