// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// GendersColumns holds the columns for the "genders" table.
	GendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gender_name", Type: field.TypeString},
	}
	// GendersTable holds the schema information for the "genders" table.
	GendersTable = &schema.Table{
		Name:        "genders",
		Columns:     GendersColumns,
		PrimaryKey:  []*schema.Column{GendersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ProvincesColumns holds the columns for the "provinces" table.
	ProvincesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "province_name", Type: field.TypeString},
	}
	// ProvincesTable holds the schema information for the "provinces" table.
	ProvincesTable = &schema.Table{
		Name:        "provinces",
		Columns:     ProvincesColumns,
		PrimaryKey:  []*schema.Column{ProvincesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "identity_card", Type: field.TypeInt},
		{Name: "password", Type: field.TypeString},
		{Name: "confirm_password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "phone", Type: field.TypeInt},
		{Name: "date_of_birth", Type: field.TypeInt},
		{Name: "gender_gender_id", Type: field.TypeInt, Nullable: true},
		{Name: "province_province_id", Type: field.TypeInt, Nullable: true},
		{Name: "user_type_user_type_id", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "users_genders_Gender_ID",
				Columns: []*schema.Column{UsersColumns[9]},

				RefColumns: []*schema.Column{GendersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_provinces_Province_ID",
				Columns: []*schema.Column{UsersColumns[10]},

				RefColumns: []*schema.Column{ProvincesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_user_types_UserType_ID",
				Columns: []*schema.Column{UsersColumns[11]},

				RefColumns: []*schema.Column{UserTypesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserTypesColumns holds the columns for the "user_types" table.
	UserTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_type_name", Type: field.TypeString},
	}
	// UserTypesTable holds the schema information for the "user_types" table.
	UserTypesTable = &schema.Table{
		Name:        "user_types",
		Columns:     UserTypesColumns,
		PrimaryKey:  []*schema.Column{UserTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GendersTable,
		ProvincesTable,
		UsersTable,
		UserTypesTable,
	}
)

func init() {
	UsersTable.ForeignKeys[0].RefTable = GendersTable
	UsersTable.ForeignKeys[1].RefTable = ProvincesTable
	UsersTable.ForeignKeys[2].RefTable = UserTypesTable
}
