// Code generated by entc, DO NOT EDIT.

package usertype

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/james/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// UserTypeName applies equality check predicate on the "UserType_name" field. It's identical to UserTypeNameEQ.
func UserTypeName(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameEQ applies the EQ predicate on the "UserType_name" field.
func UserTypeNameEQ(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameNEQ applies the NEQ predicate on the "UserType_name" field.
func UserTypeNameNEQ(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameIn applies the In predicate on the "UserType_name" field.
func UserTypeNameIn(vs ...string) predicate.UserType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUserTypeName), v...))
	})
}

// UserTypeNameNotIn applies the NotIn predicate on the "UserType_name" field.
func UserTypeNameNotIn(vs ...string) predicate.UserType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUserTypeName), v...))
	})
}

// UserTypeNameGT applies the GT predicate on the "UserType_name" field.
func UserTypeNameGT(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameGTE applies the GTE predicate on the "UserType_name" field.
func UserTypeNameGTE(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameLT applies the LT predicate on the "UserType_name" field.
func UserTypeNameLT(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameLTE applies the LTE predicate on the "UserType_name" field.
func UserTypeNameLTE(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameContains applies the Contains predicate on the "UserType_name" field.
func UserTypeNameContains(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameHasPrefix applies the HasPrefix predicate on the "UserType_name" field.
func UserTypeNameHasPrefix(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameHasSuffix applies the HasSuffix predicate on the "UserType_name" field.
func UserTypeNameHasSuffix(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameEqualFold applies the EqualFold predicate on the "UserType_name" field.
func UserTypeNameEqualFold(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldUserTypeName), v))
	})
}

// UserTypeNameContainsFold applies the ContainsFold predicate on the "UserType_name" field.
func UserTypeNameContainsFold(v string) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldUserTypeName), v))
	})
}

// HasUserTypeID applies the HasEdge predicate on the "UserType_ID" edge.
func HasUserTypeID() predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTypeIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserTypeIDTable, UserTypeIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserTypeIDWith applies the HasEdge predicate on the "UserType_ID" edge with a given conditions (other predicates).
func HasUserTypeIDWith(preds ...predicate.User) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTypeIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserTypeIDTable, UserTypeIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.UserType) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.UserType) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserType) predicate.UserType {
	return predicate.UserType(func(s *sql.Selector) {
		p(s.Not())
	})
}
