// Code generated by entc, DO NOT EDIT.

package province

const (
	// Label holds the string label denoting the province type in the database.
	Label = "province"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvinceName holds the string denoting the province_name field in the database.
	FieldProvinceName = "province_name"

	// EdgeProvinceID holds the string denoting the province_id edge name in mutations.
	EdgeProvinceID = "Province_ID"

	// Table holds the table name of the province in the database.
	Table = "provinces"
	// ProvinceIDTable is the table the holds the Province_ID relation/edge.
	ProvinceIDTable = "users"
	// ProvinceIDInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ProvinceIDInverseTable = "users"
	// ProvinceIDColumn is the table column denoting the Province_ID relation/edge.
	ProvinceIDColumn = "province_province_id"
)

// Columns holds all SQL columns for province fields.
var Columns = []string{
	FieldID,
	FieldProvinceName,
}

var (
	// ProvinceNameValidator is a validator for the "Province_Name" field. It is called by the builders before save.
	ProvinceNameValidator func(string) error
)
