// Code generated by entc, DO NOT EDIT.

package province

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/james/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ProvinceName applies equality check predicate on the "Province_Name" field. It's identical to ProvinceNameEQ.
func ProvinceName(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameEQ applies the EQ predicate on the "Province_Name" field.
func ProvinceNameEQ(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameNEQ applies the NEQ predicate on the "Province_Name" field.
func ProvinceNameNEQ(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameIn applies the In predicate on the "Province_Name" field.
func ProvinceNameIn(vs ...string) predicate.Province {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Province(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldProvinceName), v...))
	})
}

// ProvinceNameNotIn applies the NotIn predicate on the "Province_Name" field.
func ProvinceNameNotIn(vs ...string) predicate.Province {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Province(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldProvinceName), v...))
	})
}

// ProvinceNameGT applies the GT predicate on the "Province_Name" field.
func ProvinceNameGT(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameGTE applies the GTE predicate on the "Province_Name" field.
func ProvinceNameGTE(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameLT applies the LT predicate on the "Province_Name" field.
func ProvinceNameLT(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameLTE applies the LTE predicate on the "Province_Name" field.
func ProvinceNameLTE(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameContains applies the Contains predicate on the "Province_Name" field.
func ProvinceNameContains(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameHasPrefix applies the HasPrefix predicate on the "Province_Name" field.
func ProvinceNameHasPrefix(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameHasSuffix applies the HasSuffix predicate on the "Province_Name" field.
func ProvinceNameHasSuffix(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameEqualFold applies the EqualFold predicate on the "Province_Name" field.
func ProvinceNameEqualFold(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldProvinceName), v))
	})
}

// ProvinceNameContainsFold applies the ContainsFold predicate on the "Province_Name" field.
func ProvinceNameContainsFold(v string) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldProvinceName), v))
	})
}

// HasProvinceID applies the HasEdge predicate on the "Province_ID" edge.
func HasProvinceID() predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProvinceIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProvinceIDTable, ProvinceIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProvinceIDWith applies the HasEdge predicate on the "Province_ID" edge with a given conditions (other predicates).
func HasProvinceIDWith(preds ...predicate.User) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProvinceIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProvinceIDTable, ProvinceIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Province) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Province) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Province) predicate.Province {
	return predicate.Province(func(s *sql.Selector) {
		p(s.Not())
	})
}
