// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGenderName holds the string denoting the gender_name field in the database.
	FieldGenderName = "gender_name"

	// EdgeGenderID holds the string denoting the gender_id edge name in mutations.
	EdgeGenderID = "Gender_ID"

	// Table holds the table name of the gender in the database.
	Table = "genders"
	// GenderIDTable is the table the holds the Gender_ID relation/edge.
	GenderIDTable = "users"
	// GenderIDInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	GenderIDInverseTable = "users"
	// GenderIDColumn is the table column denoting the Gender_ID relation/edge.
	GenderIDColumn = "gender_gender_id"
)

// Columns holds all SQL columns for gender fields.
var Columns = []string{
	FieldID,
	FieldGenderName,
}

var (
	// GenderNameValidator is a validator for the "Gender_Name" field. It is called by the builders before save.
	GenderNameValidator func(string) error
)
